-- MySQL Script generated by MySQL Workbench
-- Wed Mar 23 14:31:10 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema uie
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `uie` ;

-- -----------------------------------------------------
-- Schema uie
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `uie` DEFAULT CHARACTER SET utf8 ;
USE `uie` ;

-- -----------------------------------------------------
-- Table `uie`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`category` ;

CREATE TABLE IF NOT EXISTS `uie`.`category` (
  `id_category` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(250) NULL,
  `description` VARCHAR(1000) NULL,
  PRIMARY KEY (`id_category`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`website`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`website` ;

CREATE TABLE IF NOT EXISTS `uie`.`website` (
  `id_website` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(200) NULL,
  `description` VARCHAR(1000) NULL COMMENT '		',
  `base_url` VARCHAR(200) NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id_website`),
  UNIQUE INDEX `baseUrl_UNIQUE` (`base_url` ASC),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`schema_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`schema_mapping` ;

CREATE TABLE IF NOT EXISTS `uie`.`schema_mapping` (
  `id_schema` INT NOT NULL AUTO_INCREMENT,
  `fk_category_website` INT NULL,
  `schema_defination` VARCHAR(2000) NULL,
  `version` INT NULL,
  `createdAt` DATETIME NULL,
  `updatedAt` DATETIME NULL,
  PRIMARY KEY (`id_schema`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`category_website_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`category_website_mapping` ;

CREATE TABLE IF NOT EXISTS `uie`.`category_website_mapping` (
  `id_category_has_website_master` INT NOT NULL AUTO_INCREMENT,
  `fk_category` INT NULL,
  `fk_website` INT NULL,
  INDEX `fk_category_has_website_website1_idx` (`fk_website` ASC),
  INDEX `fk_category_has_website_category_idx` (`fk_category` ASC),
  PRIMARY KEY (`id_category_has_website_master`),
  CONSTRAINT `fk_category_has_website_category`
    FOREIGN KEY (`fk_category`)
    REFERENCES `uie`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_category_has_website_website1`
    FOREIGN KEY (`fk_website`)
    REFERENCES `uie`.`website` (`id_website`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`stage_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`stage_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`stage_master` (
  `id_stage_master` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_stage_master`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`run_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`run_details` ;

CREATE TABLE IF NOT EXISTS `uie`.`run_details` (
  `id_run_details` INT NOT NULL AUTO_INCREMENT,
  `fk_category_website_mapping` INT NULL,
  `fk_schema_mapping` INT NULL,
  `fk_stage` INT NULL,
  `file_name` VARCHAR(45) NULL,
  `start_time` DATETIME NULL,
  `end_time` DATETIME NULL,
  `total_number_of_records` INT NULL,
  `valid_records` INT NULL,
  `invalid_records` VARCHAR(45) NULL,
  `invalid_records_path` VARCHAR(45) NULL,
  `schema_mapping_id_schema` INT NOT NULL,
  `category_has_website_master_id_category_has_website_master` INT NOT NULL,
  `stage_master_id_stage_master` INT NOT NULL,
  PRIMARY KEY (`id_run_details`, `schema_mapping_id_schema`, `category_has_website_master_id_category_has_website_master`, `stage_master_id_stage_master`),
  INDEX `fk_run_details_schema_mapping1_idx` (`schema_mapping_id_schema` ASC),
  INDEX `fk_run_details_category_has_website_master1_idx` (`category_has_website_master_id_category_has_website_master` ASC),
  INDEX `fk_run_details_stage_master1_idx` (`stage_master_id_stage_master` ASC),
  CONSTRAINT `fk_run_details_schema_mapping1`
    FOREIGN KEY (`schema_mapping_id_schema`)
    REFERENCES `uie`.`schema_mapping` (`id_schema`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_run_details_category_has_website_master1`
    FOREIGN KEY (`category_has_website_master_id_category_has_website_master`)
    REFERENCES `uie`.`category_website_mapping` (`id_category_has_website_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_run_details_stage_master1`
    FOREIGN KEY (`stage_master_id_stage_master`)
    REFERENCES `uie`.`stage_master` (`id_stage_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`severity`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`severity` ;

CREATE TABLE IF NOT EXISTS `uie`.`severity` (
  `id_severity` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_severity`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`error_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`error_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`error_master` (
  `id_error_master` INT NOT NULL AUTO_INCREMENT,
  `fk_severity` INT NULL,
  `code` INT NULL,
  `description` VARCHAR(1000) NULL,
  `resolution_guideline` VARCHAR(2000) NULL,
  `severity_id_severity` INT NOT NULL,
  PRIMARY KEY (`id_error_master`, `severity_id_severity`),
  UNIQUE INDEX `code_UNIQUE` (`code` ASC),
  INDEX `fk_error_master_severity1_idx` (`severity_id_severity` ASC),
  CONSTRAINT `fk_error_master_severity1`
    FOREIGN KEY (`severity_id_severity`)
    REFERENCES `uie`.`severity` (`id_severity`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`schedule`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`schedule` ;

CREATE TABLE IF NOT EXISTS `uie`.`schedule` (
  `id_schedule` INT NOT NULL AUTO_INCREMENT,
  `fk_category_website` VARCHAR(45) NULL,
  `frequency` VARCHAR(45) NULL,
  `status` INT NULL,
  `category_has_website_master_id_category_has_website_master` INT NOT NULL,
  PRIMARY KEY (`id_schedule`, `category_has_website_master_id_category_has_website_master`),
  UNIQUE INDEX `fk_category_website_UNIQUE` (`fk_category_website` ASC),
  INDEX `fk_schedule_category_has_website_master1_idx` (`category_has_website_master_id_category_has_website_master` ASC),
  CONSTRAINT `fk_schedule_category_has_website_master1`
    FOREIGN KEY (`category_has_website_master_id_category_has_website_master`)
    REFERENCES `uie`.`category_website_mapping` (`id_category_has_website_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`error_details`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`error_details` ;

CREATE TABLE IF NOT EXISTS `uie`.`error_details` (
  `id_error_details` INT NOT NULL AUTO_INCREMENT,
  `fk_run_details` INT NULL,
  `fk_error_code` INT NULL,
  `occurance_count` INT NULL,
  `run_details_id_run_details` INT NOT NULL,
  `error_master_id_error_master` INT NOT NULL,
  PRIMARY KEY (`id_error_details`, `run_details_id_run_details`, `error_master_id_error_master`),
  INDEX `fk_error_details_run_details1_idx` (`run_details_id_run_details` ASC),
  INDEX `fk_error_details_error_master1_idx` (`error_master_id_error_master` ASC),
  CONSTRAINT `fk_error_details_run_details1`
    FOREIGN KEY (`run_details_id_run_details`)
    REFERENCES `uie`.`run_details` (`id_run_details`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_error_details_error_master1`
    FOREIGN KEY (`error_master_id_error_master`)
    REFERENCES `uie`.`error_master` (`id_error_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`social_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`social_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`social_master` (
  `id_social_master` INT NOT NULL,
  `name` VARCHAR(100) NULL,
  `base_url` VARCHAR(150) NULL,
  PRIMARY KEY (`id_social_master`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC),
  UNIQUE INDEX `base_url_UNIQUE` (`base_url` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`payment_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`payment_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`payment_master` (
  `id_payment_master` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_payment_master`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`business_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`business_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`business_master` (
  `id_business_master` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(255) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`id_business_master`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`seller` ;

CREATE TABLE IF NOT EXISTS `uie`.`seller` (
  `id_seller` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `fk_business_master` INT NULL,
  `vintage` INT NULL,
  `no_of_directors` INT NULL,
  `business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_seller`, `business_master_id_business_master`),
  INDEX `fk_seller_business_master1_idx` (`business_master_id_business_master` ASC),
  CONSTRAINT `fk_seller_business_master1`
    FOREIGN KEY (`business_master_id_business_master`)
    REFERENCES `uie`.`business_master` (`id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`owner`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`owner` ;

CREATE TABLE IF NOT EXISTS `uie`.`owner` (
  `id_owner` INT NOT NULL AUTO_INCREMENT,
  `fk_seller` INT NULL,
  `name` VARCHAR(255) NULL,
  `designation` VARCHAR(255) NULL,
  `pan` VARCHAR(45) NULL,
  `influencer` INT NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_owner`, `seller_id_seller`, `seller_business_master_id_business_master`),
  UNIQUE INDEX `pan_UNIQUE` (`pan` ASC),
  INDEX `fk_owner_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_owner_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`physical_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`physical_store` ;

CREATE TABLE IF NOT EXISTS `uie`.`physical_store` (
  `id_physical_store` INT NOT NULL,
  `fk_seller` INT NULL,
  `address` VARCHAR(45) NULL,
  `location_lat` DECIMAL(9,6) NULL,
  `location_lng` DECIMAL(9,6) NULL,
  `size` INT NULL,
  `no_of_employees` INT NULL,
  `wifi` TINYINT(1) NULL,
  `weekly off` VARCHAR(255) NULL,
  `office hours` VARCHAR(500) NULL,
  `vintage` INT NULL,
  `aggr_rating` DECIMAL(3,2) NULL,
  `total_ratings` INT NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  `seller_id_seller1` INT NOT NULL,
  `seller_business_master_id_business_master1` INT NOT NULL,
  PRIMARY KEY (`id_physical_store`, `seller_id_seller`, `seller_business_master_id_business_master`),
  INDEX `fk_physical_store_seller1_idx` (`seller_id_seller1` ASC, `seller_business_master_id_business_master1` ASC),
  CONSTRAINT `fk_physical_store_seller1`
    FOREIGN KEY (`seller_id_seller1` , `seller_business_master_id_business_master1`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`online_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`online_store` ;

CREATE TABLE IF NOT EXISTS `uie`.`online_store` (
  `id_online_store` INT NOT NULL AUTO_INCREMENT,
  `fk_seller` INT NULL,
  `url` VARCHAR(500) NULL,
  `vintage` INT NULL,
  `aggr_rating` DECIMAL(3,2) NULL,
  `total_ratings` INT NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_online_store`),
  INDEX `fk_online_store_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_online_store_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`user_feedback`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`user_feedback` ;

CREATE TABLE IF NOT EXISTS `uie`.`user_feedback` (
  `id_user_feedback` INT NOT NULL AUTO_INCREMENT,
  `fk_physical_store` INT ZEROFILL NULL,
  `fk_online_store` INT ZEROFILL NULL,
  `rating` DECIMAL(5,3) NULL,
  `comment` VARCHAR(2000) NULL,
  `physical_store_id_physical_store` INT NOT NULL,
  `physical_store_seller_id_seller` INT NOT NULL,
  `physical_store_seller_business_master_id_business_master` INT NOT NULL,
  `online_store_id_online_store` INT NOT NULL,
  PRIMARY KEY (`id_user_feedback`),
  INDEX `fk_user_feedback_physical_store1_idx` (`physical_store_id_physical_store` ASC, `physical_store_seller_id_seller` ASC, `physical_store_seller_business_master_id_business_master` ASC),
  INDEX `fk_user_feedback_online_store1_idx` (`online_store_id_online_store` ASC),
  CONSTRAINT `fk_user_feedback_physical_store1`
    FOREIGN KEY (`physical_store_id_physical_store` , `physical_store_seller_id_seller` , `physical_store_seller_business_master_id_business_master`)
    REFERENCES `uie`.`physical_store` (`id_physical_store` , `seller_id_seller` , `seller_business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_user_feedback_online_store1`
    FOREIGN KEY (`online_store_id_online_store`)
    REFERENCES `uie`.`online_store` (`id_online_store`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`sale_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`sale_info` ;

CREATE TABLE IF NOT EXISTS `uie`.`sale_info` (
  `id_sale_info` INT NOT NULL AUTO_INCREMENT,
  `fk_seller` INT NULL,
  `fk_payment_master` INT NULL,
  `sale_amount` DECIMAL(20,2) NULL,
  `stmt_start_date` DATETIME NULL,
  `stmt_end_date` DATETIME NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_sale_info`, `seller_id_seller`, `seller_business_master_id_business_master`),
  INDEX `fk_sale_info_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_sale_info_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`social_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`social_info` ;

CREATE TABLE IF NOT EXISTS `uie`.`social_info` (
  `id_social_info` INT NOT NULL AUTO_INCREMENT,
  `fk_seller` INT NULL,
  `fk_social_master` INT NULL,
  `social_url` VARCHAR(500) NULL,
  `social_master_id_social_master` INT NOT NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_social_info`, `social_master_id_social_master`, `seller_id_seller`, `seller_business_master_id_business_master`),
  UNIQUE INDEX `social_url_UNIQUE` (`social_url` ASC),
  INDEX `fk_social_info_social_master1_idx` (`social_master_id_social_master` ASC),
  INDEX `fk_social_info_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_social_info_social_master1`
    FOREIGN KEY (`social_master_id_social_master`)
    REFERENCES `uie`.`social_master` (`id_social_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_social_info_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`phone_category_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`phone_category_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`phone_category_master` (
  `id_phone_category_master` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(100) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_phone_category_master`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`dail_info`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`dail_info` ;

CREATE TABLE IF NOT EXISTS `uie`.`dail_info` (
  `id_dail_info` INT NOT NULL,
  `fk_owner` INT NULL,
  `fk_phone_category_master` INT NULL,
  `is_dnd` TINYINT(1) NULL,
  `is_verified` TINYINT(1) NULL,
  `phone_category_master_id_phone_category_master` INT NOT NULL,
  `owner_id_owner` INT NOT NULL,
  `owner_seller_id_seller` INT NOT NULL,
  `owner_seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_dail_info`, `phone_category_master_id_phone_category_master`, `owner_id_owner`, `owner_seller_id_seller`, `owner_seller_business_master_id_business_master`),
  INDEX `fk_dail_info_phone_category_master1_idx` (`phone_category_master_id_phone_category_master` ASC),
  INDEX `fk_dail_info_owner1_idx` (`owner_id_owner` ASC, `owner_seller_id_seller` ASC, `owner_seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_dail_info_phone_category_master1`
    FOREIGN KEY (`phone_category_master_id_phone_category_master`)
    REFERENCES `uie`.`phone_category_master` (`id_phone_category_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_dail_info_owner1`
    FOREIGN KEY (`owner_id_owner` , `owner_seller_id_seller` , `owner_seller_business_master_id_business_master`)
    REFERENCES `uie`.`owner` (`id_owner` , `seller_id_seller` , `seller_business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`customer_touchpoint`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`customer_touchpoint` ;

CREATE TABLE IF NOT EXISTS `uie`.`customer_touchpoint` (
  `id_customer_touchpoint` INT NOT NULL AUTO_INCREMENT,
  `fk_dial_info` INT NULL,
  `call_date` DATETIME NULL,
  `call_summary` VARCHAR(2000) NULL,
  `dail_info_id_dail_info` INT NOT NULL,
  `dail_info_phone_category_master_id_phone_category_master` INT NOT NULL,
  PRIMARY KEY (`id_customer_touchpoint`, `dail_info_id_dail_info`, `dail_info_phone_category_master_id_phone_category_master`),
  INDEX `fk_customer_touchpoint_dail_info1_idx` (`dail_info_id_dail_info` ASC, `dail_info_phone_category_master_id_phone_category_master` ASC),
  CONSTRAINT `fk_customer_touchpoint_dail_info1`
    FOREIGN KEY (`dail_info_id_dail_info` , `dail_info_phone_category_master_id_phone_category_master`)
    REFERENCES `uie`.`dail_info` (`id_dail_info` , `phone_category_master_id_phone_category_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`email`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`email` ;

CREATE TABLE IF NOT EXISTS `uie`.`email` (
  `id_email` INT NOT NULL AUTO_INCREMENT,
  `fk_owner` INT NULL,
  `fk_email_type_master` INT NULL,
  `email` VARCHAR(45) NULL,
  `is_verified` TINYINT(1) NULL,
  `owner_id_owner` INT NOT NULL,
  `owner_seller_id_seller` INT NOT NULL,
  `owner_seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`id_email`, `owner_id_owner`, `owner_seller_id_seller`, `owner_seller_business_master_id_business_master`),
  INDEX `fk_email_owner1_idx` (`owner_id_owner` ASC, `owner_seller_id_seller` ASC, `owner_seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_email_owner1`
    FOREIGN KEY (`owner_id_owner` , `owner_seller_id_seller` , `owner_seller_business_master_id_business_master`)
    REFERENCES `uie`.`owner` (`id_owner` , `seller_id_seller` , `seller_business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`email_type_master`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`email_type_master` ;

CREATE TABLE IF NOT EXISTS `uie`.`email_type_master` (
  `id_email_type_master` INT NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(45) NULL,
  `description` VARCHAR(500) NULL,
  PRIMARY KEY (`id_email_type_master`),
  UNIQUE INDEX `type_UNIQUE` (`type` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`payment_master_has_seller`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`payment_master_has_seller` ;

CREATE TABLE IF NOT EXISTS `uie`.`payment_master_has_seller` (
  `payment_master_id_payment_master` INT NOT NULL,
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  PRIMARY KEY (`payment_master_id_payment_master`, `seller_id_seller`, `seller_business_master_id_business_master`),
  INDEX `fk_payment_master_has_seller_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  INDEX `fk_payment_master_has_seller_payment_master1_idx` (`payment_master_id_payment_master` ASC),
  CONSTRAINT `fk_payment_master_has_seller_payment_master1`
    FOREIGN KEY (`payment_master_id_payment_master`)
    REFERENCES `uie`.`payment_master` (`id_payment_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_payment_master_has_seller_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`seller_has_category_website_mapping`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`seller_has_category_website_mapping` ;

CREATE TABLE IF NOT EXISTS `uie`.`seller_has_category_website_mapping` (
  `seller_id_seller` INT NOT NULL,
  `seller_business_master_id_business_master` INT NOT NULL,
  `category_website_mapping_id_category_has_website_master` INT NOT NULL,
  PRIMARY KEY (`seller_id_seller`, `seller_business_master_id_business_master`, `category_website_mapping_id_category_has_website_master`),
  INDEX `fk_seller_has_category_website_mapping_category_website_map_idx` (`category_website_mapping_id_category_has_website_master` ASC),
  INDEX `fk_seller_has_category_website_mapping_seller1_idx` (`seller_id_seller` ASC, `seller_business_master_id_business_master` ASC),
  CONSTRAINT `fk_seller_has_category_website_mapping_seller1`
    FOREIGN KEY (`seller_id_seller` , `seller_business_master_id_business_master`)
    REFERENCES `uie`.`seller` (`id_seller` , `business_master_id_business_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_seller_has_category_website_mapping_category_website_mappi1`
    FOREIGN KEY (`category_website_mapping_id_category_has_website_master`)
    REFERENCES `uie`.`category_website_mapping` (`id_category_has_website_master`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `uie`.`manual_data_collection`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `uie`.`manual_data_collection` ;

CREATE TABLE IF NOT EXISTS `uie`.`manual_data_collection` (
  `id_manual_data_collection` INT NOT NULL AUTO_INCREMENT,
  `merchant_name` VARCHAR(300) NOT NULL,
  `contact_person` VARCHAR(300) NOT NULL,
  `telephone` VARCHAR(100) NULL,
  `email` VARCHAR(200) NULL,
  `photograph_url` VARCHAR(400) NULL,
  `appointment_time` VARCHAR(400) NULL,
  `address` VARCHAR(1500) NULL,
  `address_locality` VARCHAR(200) NULL,
  `city` VARCHAR(200) NULL,
  `state` VARCHAR(100) NULL,
  `country` VARCHAR(100) NULL,
  `pincode` INT NULL,
  `latitude` DOUBLE NULL,
  `longitude` DOUBLE NULL,
  `fk_id_category` INT NOT NULL,
  PRIMARY KEY (`id_manual_data_collection`, `fk_id_category`),
  INDEX `fk_manual_data_collection_category1_idx` (`fk_id_category` ASC),
  CONSTRAINT `fk_manual_data_collection_category1`
    FOREIGN KEY (`fk_id_category`)
    REFERENCES `uie`.`category` (`id_category`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
